## roles/ansible-role-saltstack/tasks/main.yml
# vim:ft=ansible:
---
- include_tasks: "{{ salt_distro_include }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ default }}.yml"
  loop_control:
    loop_var: salt_distro_include
...
